name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: DemoSolution
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org792134b3.crm4.dynamics.com'
  CLIENT_ID: '6a5754ee-a779-42e0-b97f-7e7e4ca3369d'
  TENANT_ID: '1ba735a2-4eb2-4f59-9e8d-ebc69a922c0a'
  solution_exported_folder: out/exported/
  solution_folder: out/solutions/
  solution_target_folder: solutions/
  solution_shipping_folder: out/ship/

jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Get current date
      run: |
        $date=Get-Date -Format "ddMMyyyy-HHmm"
        echo ("DATE=$date") >> $env:GITHUB_ENV

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ env.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ env.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ env.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ env.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ env.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        branch-name: ${{ github.event.inputs.solution_name }}-${{ env.DATE }}
        repo-token: ${{ secrets.PAT_TVONMENT }}
        allow-empty-commit: true

    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.solution_name }}-${{ env.DATE }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: export-managed solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ env.solution_shipping_folder}}/${{ github.event.inputs.solution_name }}_managed.zip
        managed: true

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.PAT_TVONMENT }}
