name: release-solution-to-prod
# Reusable workflow
# convert solution to managed (using a build PowerPlatform environment for the conversion)
# upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  workflow_call:
    inputs: 
      #Do Not change these values
      #Values are set by the caller
      #caller sample: release-action-call.ymnl
      solution_name:
        description: 'The solution name.'
        type: string
        default: DemoSolution

env:
      #Update your values here
      ENVIRONMENT_URL: 'https://orgd910365a.crm4.dynamics.com'
      CLIENT_ID: '6a5754ee-a779-42e0-b97f-7e7e4ca3369d'
      TENANT_ID: '1ba735a2-4eb2-4f59-9e8d-ebc69a922c0a'
      solution_release_folder: out/release
      solution_source_folder: solutions/

jobs:
  release-to-prod:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ inputs.solution_source_folder}}/${{ inputs.solution_name }}
        solution-file: ${{ inputs.solution_release_folder}}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{inputs.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{inputs.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{inputs.TENANT_ID}}
        solution-file: ${{ inputs.solution_release_folder}}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
        convert-to-manage: true