name: release-solution-to-prod
# upload the solution to deploy to the PROD environment

on:
  workflow_dispatch:
    inputs: 
      solution_name:
        description: 'The solution name.'
        type: string
        default: DemoSolution

env:
      #Update your values here
      ENVIRONMENT_URL: 'https://orgd910365a.crm4.dynamics.com'
      CLIENT_ID: '6a5754ee-a779-42e0-b97f-7e7e4ca3369d'
      TENANT_ID: '1ba735a2-4eb2-4f59-9e8d-ebc69a922c0a'
      solution_release_folder: solutions/

jobs:
  release-to-prod:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ env.solution_release_folder}}/${{ inputs.solution_name }}_managed.zip
        force-overwrite: true
        publish-changes: true
