# This is a basic workflow to help you get started with Actions

name: CI Power Platform Solution

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CLIENT_ID: 6a5754ee-a779-42e0-b97f-7e7e4ca3369d
  TENANT_ID: 1ba735a2-4eb2-4f59-9e8d-ebc69a922c0a
  ENVIRONMENT_URL: https://org792134b3.crm4.dynamics.com
  dest-env-url: https://orgd910365a.crm4.dynamics.com

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: powerplatform-actions
        uses: microsoft/powerplatform-actions@v0.10.2

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.POWERPLATFORMSPN }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-name: DemoSolution
          solution-output-file: 'demoSolution.zip'
          working-directory: 'out'

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: 'out/demoSolution.zip'
          solution-folder: 'out/solutions/demoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

